### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by jakeloo** [zzh8829/test#1]
hi, how do i use it?

**Comment by theonlyjohnny** [comment]
+1

**Comment by zzh8829** [comment]
Dear open source back seat gamers. if you would like to contribute please open a pull request instead of harassing the original creator for their hard work.

**Comment by theonlyjohnny** [comment]
toxic

**Comment by zzh8829** [comment]
no u

uwu owo 
![image](https://user-images.githubusercontent.com/2136136/95133151-b823e580-0715-11eb-9edd-ca9423826da0.png)

**Comment by derekpankaew** [comment]
+2

**Comment by erik-dunteman** [comment]
Could you reopen this? No reason in particular.

**Comment by derekpankaew** [comment]
I 100% agree, please re-open

**Comment by theonlyjohnny** [comment]
This lack of flexibility and refusal to help others learn is exactly what’s killing the open source community. Shame on you for hating on a simple-minded n00b like @jakeloo, who is simply trying to learn the ways of code
